repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
      - id: prettier
        args: ["--use-tabs"]
        additional_dependencies:
          - prettier-plugin-svelte@2.5.0
# TODO: setup eslint
#  - repo: https://github.com/pre-commit/mirrors-eslint
#    rev: v7.0.0
#    hooks:
#      - id: eslint
#        additional_dependencies:
#          - eslint@7.0.0
#          - eslint-config-google@0.14.0
#          - eslint-loader@4.0.2
