<script>
	import { DefaultApi } from "./gen";
	import ajv from "ajv";
	import openapi from "./openapi.json";

	// http client generated by openapi-generator-cli from openapi.json
	// https://openapi-generator.tech/docs/generators/typescript-fetch
	let api = new DefaultApi();

	// https://ajv.js.org/
	const schema = ajv({ schemas: openapi.components.schemas, allErrors: true });

	let result = null;

	let user = { name: "ab", age: 17 };

	async function createUser() {
		result = await api.createUser({ createUserRequest: user });
	}

	let ok;
	let validationErrors;
	$: {
		ok = schema.validate("CreateUserRequest", user);
		validationErrors = schema.errors;
	}
</script>

<div>
	<label>Name:<input bind:value={user.name} /></label>
	<label>Age:<input type="number" bind:value={user.age} /></label>
	<button disabled={!ok} on:click={createUser} type="button">Create User</button
	>
</div>

{#if result}
	<p>Result: {JSON.stringify(result)}</p>
{/if}

{#if validationErrors}
	<p>Validation Errors:</p>
	<pre>{JSON.stringify(validationErrors, null, 2)}</pre>
{/if}
